# Generated by Django 4.2.9 on 2024-06-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
