# Generated by Django 4.2.9 on 2024-01-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sign_in_out", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="EmailAddress",),
        migrations.DeleteModel(name="Password",),
    ]
